printBanner: true
dotfiles:
  use-git: true
  git-repository: "B1TC0R3/dotfiles"
  clone-to: "/home/b1tc0r3/Documents/Test"
  file-bindings: [
    {
      from: "/home/b1tc0r3/.config/bat/config",
      to: "/home/b1tc0r3/Documents/Test/bat/config"
    },
    {
      from: "/home/b1tc0r3/.config/picom/picom.conf",
      to: "/home/b1tc0r3/Documents/dotfiles/picom/picom.conf"
    }
  ]
